services:
  db:
    image: mysql:8.0
    container_name: pos_db
    restart: always
    environment:
      MYSQL_DATABASE: pos_db
      MYSQL_USER: pos_user
      MYSQL_PASSWORD: pos_password
      MYSQL_ROOT_PASSWORD: pos_root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - app-net

  backend:
    build:
      context: ./enterprise-pos/backend
      dockerfile: Dockerfile
    container_name: pos_backend
    restart: always
    environment:
      - DB_NAME=pos_db
      - DB_USER=pos_user
      - DB_PASSWORD=pos_password
      - DB_HOST=db
      - DB_PORT=3306
      - SECRET_KEY=django-insecure-j2-vps-deploy-muhammad-2026
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - CORS_ALLOW_ALL_ORIGINS=True
    depends_on:
      - db
    volumes:
      - django_static:/app/staticfiles
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos_frontend
    restart: always
    labels:
      - traefik.enable=true
      - "traefik.http.routers.sansons.rule=Host(`sansons.shop`) || Host(`www.sansons.shop`)"
      - traefik.http.routers.sansons.entrypoints=websecure
      - traefik.http.routers.sansons.tls=true
      - traefik.http.routers.sansons.tls.certresolver=mytlschallenge
      - traefik.http.services.sansons.loadbalancer.server.port=80
    depends_on:
      - backend
    volumes:
      - django_static:/usr/share/nginx/html/static
    networks:
      - app-net
      - n8n_default

volumes:
  mysql_data:
  django_static:

networks:
  app-net:
  n8n_default:
    external: true
