"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-j2*b*2n5y6y-cc)mb(!u+$im#t^z!z2q3&!i(54wrwtex0qs9j')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

allowed_hosts_env = os.getenv('ALLOWED_HOSTS')
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'sansons.shop', 'www.sansons.shop']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken', # Added for Authentication/Login
    'corsheaders',
    'inventory',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # MOVED TO TOP for max reliability
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# REST Framework Global Settings (Optional but recommended for secure APIs)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        'http://127.0.0.1:5174',
        'http://localhost:5174',
        'http://127.0.0.1:5173',
        'http://localhost:5173',
    ]

CORS_ALLOW_CREDENTIALS = True

# Secure proxy SSL header for HTTPS behind reverse proxies
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:5173',
    'http://localhost:5173',
    'http://127.0.0.1:5174',
    'http://localhost:5174',
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'https://sansons.shop',
    'https://www.sansons.shop',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'pos_db'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Unfold Premium SaaS Admin Theme Configuration
UNFOLD = {
    "SITE_TITLE": "SanSons POS",
    "SITE_HEADER": "SanSons POS",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    # -- Custom CSS & JS injected into every admin page --
    "STYLES": [
        lambda request: "/static/admin/css/custom_admin.css",
    ],
    "SCRIPTS": [
        lambda request: "/static/admin/js/theme_toggle.js",
    ],
    # -- Color palette (Tailwind CSS HSL function values) --
    "COLORS": {
        "primary": {
            "50": "240 6% 97%",
            "100": "214 32% 96%",
            "200": "214 32% 91%",
            "300": "213 27% 84%",
            "400": "215 20% 65%",
            "500": "217 33% 17%",
            "600": "221 39% 11%",
            "700": "224 71% 4%",
            "800": "240 10% 6%",
            "900": "240 10% 4%",
            "950": "0 0% 0%",
        },
    },
    # -- Sidebar with Material Icons --
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Authentication",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "admin_panel_settings",
                        "link": "/admin/auth/group/",
                    },
                    {
                        "title": "API Tokens",
                        "icon": "token",
                        "link": "/admin/authtoken/tokenproxy/",
                    },
                ],
            },
            {
                "title": "Inventory",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": "/admin/inventory/product/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/inventory/category/",
                    },
                    {
                        "title": "Suppliers",
                        "icon": "local_shipping",
                        "link": "/admin/inventory/supplier/",
                    },
                    {
                        "title": "Customers",
                        "icon": "group",
                        "link": "/admin/inventory/customer/",
                    },
                    {
                        "title": "Discounts",
                        "icon": "sell",
                        "link": "/admin/inventory/discount/",
                    },
                ],
            },
            {
                "title": "Sales & Orders",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Sales",
                        "icon": "point_of_sale",
                        "link": "/admin/inventory/sale/",
                    },
                    {
                        "title": "Purchase Orders",
                        "icon": "shopping_cart",
                        "link": "/admin/inventory/purchaseorder/",
                    },
                    {
                        "title": "Expenses",
                        "icon": "receipt_long",
                        "link": "/admin/inventory/expense/",
                    },
                ],
            },
            {
                "title": "Reports",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Activity Logs",
                        "icon": "history",
                        "link": "/admin/inventory/activitylog/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "inventory.product",
                "inventory.category",
                "inventory.supplier",
            ],
            "items": [
                {
                    "title": "Products",
                    "icon": "inventory_2",
                    "link": "/admin/inventory/product/",
                },
                {
                    "title": "Categories",
                    "icon": "category",
                    "link": "/admin/inventory/category/",
                },
                {
                    "title": "Suppliers",
                    "icon": "local_shipping",
                    "link": "/admin/inventory/supplier/",
                },
            ],
        },
    ],
}
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"